-- CREATE DATABASE IF NOT EXISTS trabalho_ds2_primeiro_bim;

-- USE trabalho_ds2_primeiro_bim;

CREATE TABLE USUARIO (
  ID_USUARIO SERIAL,
  NOME VARCHAR(20) NOT NULL,
  SOBRENOME VARCHAR(50) NOT NULL,
  CPF VARCHAR(15) UNIQUE NOT NULL,
  CEP VARCHAR(15) NOT NULL,
  ENDERECO VARCHAR(60),
  NUMERO VARCHAR(8),
  BAIRRO VARCHAR(60),
  CIDADE VARCHAR(60),
  UF CHAR(2),
  EMAIL VARCHAR(50) UNIQUE NOT NULL,
  SENHA VARCHAR(20) NOT NULL,
  ATIVO BOOLEAN NOT NULL DEFAULT TRUE, -- USUARIO ATIVO OU DELETADO
  NIVEL_ACESSO INT NOT NULL DEFAULT 3,
  CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO)
) ENGINE = INNODB DEFAULT CHARSET = LATIN1;

CREATE TABLE LISTA (
  ID_LISTA SERIAL,
  ID_USUARIO INT NOT NULL,
  TITULO VARCHAR(50) NOT NULL,
  CONSTRAINT PK_LISTA PRIMARY KEY (ID_LISTA),
) ENGINE = INNODB DEFAULT CHARSET = LATIN1;

CREATE TABLE CARTAO (
  ID_CARTAO SERIAL,
  ID_LISTA INT NOT NULL, -- O CARTAO VAI ESTAR DENTRO DE ALGUMA LISTA
  ID_ULTIMO_UPDATE INT NOT NULL, -- ULTIMA PESSOA QUE ATUALIZOU O CARTAO
  ID_CRIADOR INT NOT NULL, -- QUEM CRIOU O CARTAO
  TITULO VARCHAR(50) NOT NULL, -- TITULO DO CARTAO
  CONSTRAINT PK_CARTAO PRIMARY KEY (ID_CARTAO)
) ENGINE = INNODB DEFAULT CHARSET = LATIN1;

-- CONSTRAINT FK_ESTOQUE_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)